require './lib/euler/exercise/main'

class Euler::Exercise::Number00045 < Euler::Exercise::Main
  @@number = self.to_s[-5,5].to_i
  def initialize;super(@@number);end

=begin
Problem 45:

Triangle, pentagonal, and hexagonal numbers are generated by the following formulae:
Triangle
 
 T_n=n(n+1)/2 
 
 1, 3, 6, 10, 15, ... 
Pentagonal
 
 P_n=n(3n - 1)/2 
 
 1, 5, 12, 22, 35, ... 
Hexagonal
 
 H_n=n(2n - 1) 
 
 1, 6, 15, 28, 45, ... 
It can be verified that  T_{285} = P_{165} = H_{143} = 40755 .
Find the next triangle number that is also pentagonal and hexagonal.

Source: https://projecteuler.net/problem=45
=end

  # Change __FILL_ME_IN__ so that 'my_solution' returns the correct answer.
  # Use __SKIP__ or "SKIP" to move on to the next question.
  def my_solution
    __FILL_ME_IN__
  end
end
